# ===================================================================
# CONFIGURAÇÃO PADRÃO: BANCO EM MEMÓRIA (H2)
# Roda em qualquer lugar: Codespaces ou PC do Professor sem instalar nada
# ===================================================================
spring.application.name=fintech

# Configuração da URL e credenciais do H2
spring.datasource.url=jdbc:h2:mem:velofydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Sincronização automática de Tabelas e exibição de SQL no Console
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true

# 🚨 MOTOR DE CORREÇÃO: Força a execução do data.sql na ordem correta
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

# ===================================================================
# PERFIL SEPARADO: ORACLE FIAP
# Para ativar, use: mvn spring-boot:run -Dspring-boot.run.profiles=oracle
# ===================================================================
# spring.config.activate.on-profile=oracle
# spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
# spring.datasource.username=RM567511
# spring.datasource.password=050999
# spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# spring.jpa.database-platform=org.hibernate.dialect.OracleDialect