# ===================================================================
# CONFIGURACAO BANCO EM MEMORIA (H2)
# ===================================================================
# spring.application.name=fintech
# spring.datasource.url=jdbc:h2:mem:velofydb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.show-sql=true
# spring.jpa.open-in-view=true
# spring.jpa.defer-datasource-initialization=true
# spring.sql.init.mode=always
# spring.sql.init.continue-on-error=true

# ===================================================================
# CONFIGURACAO ORACLE FIAP
# ===================================================================
spring.application.name=fintech

# Desativa a criacao automatica do Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=true

# Credenciais
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=RM567511
spring.datasource.password=050999
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect